# Configure main menu and social menu
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/890mn"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/45409103"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "Gmail"
name = "Gmail"
url = "mailto:linkjoestar402212@gmail.com"

[social.params]
icon = "mail"
